apiVersion: cndev.nl/v1beta1
kind: VolumeTracker
metadata:
  name: example-tracker
  labels:
    app.kubernetes.io/name: volumetracker
    app.kubernetes.io/part-of: disaster-recovery-operator
  annotations:
    description: "Tracks persistent volume usage and logs it"
spec:
  clusterNameKey: cluster.x-k8s.io/cluster-name # retreiving the cluster name by annotation key is required
  cloudProvider: azure 
  retention: 14 # retention in days